import { all, atualizar, contar, inserirVarios } from "@/db";
import type { Atestado, Inspecao, Militar, Usuario } from "@/db/schema";
import { hashSenha } from "@/lib/auth";
import { addDias, diasInclusive, hoje } from "@/lib/datas";

const OM_PRINCIPAL = "1º Batalhão de Polícia Militar";
const OM_APOIO = "Base Administrativa do Comando-Geral da PMRO";

let verificacao: Promise<void> | null = null;

/** Garante que o banco tenha conteúdo de demonstração (idempotente). */
export function ensureSeed(): Promise<void> {
  verificacao ??= executar().catch((erro) => {
    verificacao = null;
    throw erro;
  });
  return verificacao;
}

async function executar() {
  const total = await contar("usuarios");
  if (total > 0) return;

  // Trilha de auditoria imutável via RULEs criadas na migration sis-jis-schema.

  const senha = hashSenha("jis123");
  const [presidente, medico, secretaria, pessoal] = await inserirVarios<Usuario>("usuarios", [
      {
        nome: "Cel Med Ricardo Antunes Vilas Boas",
        login: "presidente",
        senhaHash: senha,
        papel: "admin",
        posto: "Coronel",
        crm: "CRM-RO 14820",
        especialidade: "Medicina Legal e Perícias Médicas",
        om: OM_PRINCIPAL,
        email: "presidente.jis@pm.ro.gov.br",
      },
      {
        nome: "Maj Méd Camila Ferraz Nogueira",
        login: "medico",
        senhaHash: senha,
        papel: "medico",
        posto: "Major",
        crm: "CRM-RO 22315",
        especialidade: "Ortopedia e Traumatologia",
        om: OM_PRINCIPAL,
        email: "camila.ferraz@pm.ro.gov.br",
      },
      {
        nome: "1º Sgt Ana Paula Ribeiro Souza",
        login: "secretaria",
        senhaHash: senha,
        papel: "secretaria",
        posto: "1º Sargento",
        om: OM_PRINCIPAL,
        email: "secretaria.jis@pm.ro.gov.br",
      },
      {
        nome: "2º Sgt Marcos Vinícius Prado",
        login: "pessoal",
        senhaHash: senha,
        papel: "pessoal",
        posto: "2º Sargento",
        om: OM_PRINCIPAL,
        email: "s1@pm.ro.gov.br",
      },
    ]);

  const data = hoje();

  const novosMilitares = await inserirVarios<Militar>("militares", [
      {
        re: "1045872",
        cpf: "01458723901",
        nome: "José Almeida Santana",
        nomeGuerra: "ALMEIDA",
        postoGraduacao: "3º Sargento",
        quadro: "QPPM",
        om: OM_PRINCIPAL,
        funcao: "Chefe de equipe de infantaria",
        dataNascimento: "1992-04-11",
        sexo: "M",
        tipoSanguineo: "O+",
        telefone: "(91) 98122-4477",
        email: "almeida.sgt@pm.ro.gov.br",
        dataInclusao: "2011-03-01",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1078411",
        cpf: "02244778102",
        nome: "Rafael Souza Lima",
        nomeGuerra: "R. LIMA",
        postoGraduacao: "Cabo",
        quadro: "QPPM",
        om: OM_PRINCIPAL,
        funcao: "Motorista de viatura operacional",
        dataNascimento: "1998-09-23",
        sexo: "M",
        tipoSanguineo: "A+",
        telefone: "(91) 98333-1020",
        dataInclusao: "2017-02-20",
        situacao: "agregado",
        criadoPor: secretaria.id,
      },
      {
        re: "1120933",
        cpf: "03551889204",
        nome: "Mariana Castro Barbosa",
        nomeGuerra: "M. BARBOSA",
        postoGraduacao: "2º Tenente",
        quadro: "QOPM",
        om: OM_APOIO,
        funcao: "Oficial de logística",
        dataNascimento: "1995-01-30",
        sexo: "F",
        tipoSanguineo: "B-",
        telefone: "(91) 99144-7788",
        email: "mariana.ten@pm.ro.gov.br",
        dataInclusao: "2019-06-10",
        situacao: "agregado",
        observacoes:
          "Afastamento contínuo superior a 2 anos em análise pela Junta — processo de agregação em curso.",
        criadoPor: secretaria.id,
      },
      {
        re: "1155220",
        cpf: "04112558703",
        nome: "Carlos Eduardo Pimentel",
        nomeGuerra: "PIMENTEL",
        postoGraduacao: "Soldado",
        quadro: "Efetivo Temporário",
        om: OM_PRINCIPAL,
        funcao: "Combatente de infantaria",
        dataNascimento: "2003-07-02",
        sexo: "M",
        tipoSanguineo: "AB+",
        telefone: "(91) 98777-4511",
        dataInclusao: "2022-03-01",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1002214",
        cpf: "05223884107",
        nome: "Fernanda Rocha Dias",
        nomeGuerra: "F. DIAS",
        postoGraduacao: "Capitão",
        quadro: "QOPM",
        om: OM_APOIO,
        funcao: "Comandante de companhia",
        dataNascimento: "1988-11-18",
        sexo: "F",
        tipoSanguineo: "O-",
        telefone: "(91) 98220-9090",
        dataInclusao: "2007-02-15",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1188450",
        cpf: "06884221509",
        nome: "Wagner Batista Melo",
        nomeGuerra: "W. MELO",
        postoGraduacao: "Subtenente",
        quadro: "QPPM",
        om: OM_PRINCIPAL,
        funcao: "Encarregado de material bélico",
        dataNascimento: "1979-05-06",
        sexo: "M",
        tipoSanguineo: "A-",
        telefone: "(91) 98111-3030",
        dataInclusao: "1998-03-02",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1210774",
        cpf: "07335998201",
        nome: "Lucas Ferreira Aguiar",
        nomeGuerra: "AGUIAR",
        postoGraduacao: "Cabo",
        quadro: "QPPM",
        om: OM_PRINCIPAL,
        funcao: "Operador de comunicações",
        dataNascimento: "2000-12-14",
        sexo: "M",
        tipoSanguineo: "B+",
        telefone: "(91) 99455-7080",
        dataInclusao: "2019-03-01",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1093315",
        cpf: "08117445602",
        nome: "Patrícia Lemos Cardoso",
        nomeGuerra: "P. LEMOS",
        postoGraduacao: "1º Sargento",
        quadro: "QPPM",
        om: OM_APOIO,
        funcao: "Encarregada de rancho",
        dataNascimento: "1985-03-27",
        sexo: "F",
        tipoSanguineo: "O+",
        telefone: "(91) 98640-1122",
        dataInclusao: "2004-02-20",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1233908",
        cpf: "09225887403",
        nome: "Thiago Nogueira Ramos",
        nomeGuerra: "T. RAMOS",
        postoGraduacao: "Soldado",
        quadro: "Efetivo Temporário",
        om: OM_PRINCIPAL,
        funcao: "Combatente de infantaria",
        dataNascimento: "2004-02-08",
        sexo: "M",
        tipoSanguineo: "A+",
        telefone: "(91) 99322-8877",
        dataInclusao: "2023-03-01",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1061123",
        cpf: "10447882305",
        nome: "Sérgio Mota Cavalcanti",
        nomeGuerra: "MOTA",
        postoGraduacao: "Major",
        quadro: "QOPM",
        om: OM_PRINCIPAL,
        funcao: "Subcomandante",
        dataNascimento: "1981-08-19",
        sexo: "M",
        tipoSanguineo: "B+",
        telefone: "(91) 98177-4040",
        dataInclusao: "2000-02-10",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1147702",
        cpf: "11552339807",
        nome: "Juliana Prado Teixeira",
        nomeGuerra: "J. TEIXEIRA",
        postoGraduacao: "3º Sargento",
        quadro: "Efetivo Temporário",
        om: OM_APOIO,
        funcao: "Técnica em enfermagem",
        dataNascimento: "1993-06-25",
        sexo: "F",
        tipoSanguineo: "O+",
        telefone: "(91) 99811-2244",
        dataInclusao: "2014-03-01",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
      {
        re: "1205561",
        cpf: "12664885701",
        nome: "Eduardo Pinto Vasconcelos",
        nomeGuerra: "VASCONCELOS",
        postoGraduacao: "1º Tenente",
        quadro: "QOPM",
        om: OM_PRINCIPAL,
        funcao: "Oficial de inteligência",
        dataNascimento: "1996-10-03",
        sexo: "M",
        tipoSanguineo: "A+",
        telefone: "(91) 98444-6677",
        dataInclusao: "2018-12-14",
        situacao: "ativo",
        criadoPor: secretaria.id,
      },
    ]);

  const [
    almeida,
    rafael,
    mariana,
    pimentel,
    fernanda,
    wagner,
    lucas,
    patricia,
    thiago,
    mota,
    juliana,
    eduardo,
  ] = novosMilitares;

  const novosAtestados = await inserirVarios<Atestado>("atestados", [
      {
        protocolo: `AT-${data.slice(0, 4)}-00001`,
        militarId: pimentel.id,
        dataEmissao: addDias(data, -2),
        dataApresentacao: addDias(data, -1),
        emitente: "Dr. Henrique Sales — Clínica Vida (Belém/PA)",
        cid: "S62.3",
        diasSugeridos: 21,
        descricao:
          "Fratura em punho direito após queda em instrução individual básica. Imobilizado, com orientação de repouso e retorno em 3 semanas.",
        origem: "militar",
        status: "pendente",
        criadoPor: null,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00002`,
        militarId: thiago.id,
        dataEmissao: addDias(data, -3),
        dataApresentacao: addDias(data, -3),
        emitente: "UPA Jurunas — Dra. Lúcia Menezes",
        cid: "J06.9",
        diasSugeridos: 3,
        descricao: "IVAS com febre e odinofagia. Prescrito sintomático e repouso domiciliar.",
        origem: "militar",
        status: "pendente",
        criadoPor: null,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00003`,
        militarId: juliana.id,
        dataEmissao: addDias(data, -5),
        dataApresentacao: addDias(data, -4),
        emitente: "Hospital Geral de Belém — Dr. Paulo Tavares",
        cid: "F41.1",
        diasSugeridos: 15,
        descricao:
          "Quadro de ansiedade generalizada em acompanhamento ambulatorial, com ajuste de medicação.",
        origem: "secretaria",
        status: "em_analise",
        criadoPor: secretaria.id,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00004`,
        militarId: almeida.id,
        dataEmissao: addDias(data, -18),
        dataApresentacao: addDias(data, -17),
        emitente: "Ortocenter — Dr. Felipe Arruda",
        cid: "M54.5",
        diasSugeridos: 10,
        descricao: "Lombalgia aguda após esforço em carga de material. RM sem alteração estrutural.",
        origem: "secretaria",
        status: "homologado",
        criadoPor: secretaria.id,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00005`,
        militarId: rafael.id,
        dataEmissao: addDias(data, -12),
        dataApresentacao: addDias(data, -11),
        emitente: "Hospital Geral de Belém — Dra. Ivone Braga",
        cid: "S82.4",
        diasSugeridos: 60,
        descricao:
          "Fratura de fíbula esquerda em acidente automobilístico (fora do serviço). Osteossíntese e reabilitação.",
        origem: "secretaria",
        status: "homologado",
        criadoPor: secretaria.id,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00006`,
        militarId: lucas.id,
        dataEmissao: addDias(data, -1),
        dataApresentacao: addDias(data, -1),
        emitente: "Clínica São Lucas — Dr. André Bezerra",
        cid: "K29.7",
        diasSugeridos: 5,
        descricao: "Gastrite enantematosa com vômitos. Solicitado afastamento das atividades de campo.",
        origem: "militar",
        status: "pendente",
        criadoPor: null,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00007`,
        militarId: fernanda.id,
        dataEmissao: addDias(data, -9),
        dataApresentacao: addDias(data, -9),
        emitente: "Obstetra Dra. Renata Vidal",
        cid: "O26.9",
        diasSugeridos: 30,
        descricao: "Acompanhamento gestacional de alto risco com recomendação de repouso relativo.",
        origem: "secretaria",
        status: "em_analise",
        criadoPor: secretaria.id,
      },
      {
        protocolo: `AT-${data.slice(0, 4)}-00008`,
        militarId: wagner.id,
        dataEmissao: addDias(data, -30),
        dataApresentacao: addDias(data, -29),
        emitente: "Cardiocenter — Dr. Mário Assunção",
        cid: "I10",
        diasSugeridos: 7,
        descricao: "Hipertensão arterial descompensada. Ajuste terapêutico e reavaliação em 30 dias.",
        origem: "militar",
        status: "nao_homologado",
        justificativa:
          "Atestado sem afastamento prescrito; militar avaliado como apto com restrição.",
        criadoPor: secretaria.id,
      },
    ]);

  const [atPimentel, atThiago, atJuliana, atAlmeida, atRafael, atLucas, atFernanda, atWagner] =
    novosAtestados;

  // ---- Inspeções anteriores (histórico) ----
  const novasInspecoes = await inserirVarios<Inspecao>("inspecoes", [
      {
        ataNumero: `ATA Nº 0001/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: almeida.id,
        atestadoId: atAlmeida.id,
        medicoId: medico.id,
        tipo: "inicial",
        dataInspecao: addDias(data, -16),
        parecer: "necessita_lts",
        cid: "M54.5",
        enquadramentoLegal: "Estatuto dos Policiais Militares de Rondônia — LTS",
        diasAfastamento: 10,
        dataInicio: addDias(data, -17),
        dataFim: addDias(data, -8),
        restringeAtividade: true,
        descricaoClinica:
          "Lombalgia mecânica aguda, sem déficit neurológico. Manobra de Lasègue negativa.",
        examesRealizados: "Radiografia de coluna lombar (sem alterações estruturais).",
        recomendacoes:
          "Dispensa de atividade física e de transporte de carga pesada por 30 dias.\nEvitar marcha prolongada.",
        necessitaReavaliacao: false,
        status: "publicada",
        biNumero: `BG nº 042, de ${addDias(data, -15)}`,
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        publicadoEm: new Date(),
        criadoPor: medico.id,
      },
      {
        ataNumero: `ATA Nº 0002/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: rafael.id,
        atestadoId: atRafael.id,
        medicoId: presidente.id,
        tipo: "inicial",
        dataInspecao: addDias(data, -10),
        parecer: "inapto_temporario",
        cid: "S82.4",
        enquadramentoLegal: "Estatuto dos Policiais Militares de Rondônia — Prorrogação de LTS",
        diasAfastamento: 60,
        dataInicio: addDias(data, -11),
        dataFim: addDias(data, 48),
        restringeAtividade: true,
        descricaoClinica:
          "Pós-operatório de osteossíntese de fíbula esquerda. Marcha com apoio parcial.",
        examesRealizados: "Radiografia de controle com boa consolidação parcial.",
        recomendacoes:
          "Dispensa total de atividade física.\nRestrição a direção de viatura militar.\nFisioterapia 3x/semana.",
        necessitaReavaliacao: true,
        dataReavaliacao: addDias(data, 41),
        status: "homologada",
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        criadoPor: presidente.id,
      },
      {
        ataNumero: `ATA Nº 0003/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: wagner.id,
        atestadoId: atWagner.id,
        medicoId: medico.id,
        tipo: "reavaliacao",
        dataInspecao: addDias(data, -25),
        parecer: "apto_com_restricao",
        cid: "I10",
        enquadramentoLegal: "RDPM — Dispensa de atividade",
        diasAfastamento: 0,
        dataInicio: null,
        dataFim: null,
        restringeAtividade: true,
        descricaoClinica:
          "HAS estágio 1 controlada com medicação. Ausência de lesão de órgão-alvo.",
        examesRealizados: "ECG normal; MAPA 24h com controle adequado.",
        recomendacoes: "Restrição a serviço em altura e a atividades de alto estresse térmico.",
        necessitaReavaliacao: true,
        dataReavaliacao: addDias(data, 5),
        status: "publicada",
        biNumero: `BG nº 038, de ${addDias(data, -24)}`,
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        publicadoEm: new Date(),
        criadoPor: medico.id,
      },
      {
        ataNumero: `ATA Nº 0004/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: mota.id,
        atestadoId: null,
        medicoId: presidente.id,
        tipo: "ex_officio",
        dataInspecao: addDias(data, -60),
        parecer: "apto",
        cid: null,
        enquadramentoLegal: null,
        diasAfastamento: 0,
        restringeAtividade: false,
        descricaoClinica: "Inspeção de saúde periódica anual sem alterações relevantes.",
        examesRealizados: "Hemograma, glicemia e lipidograma dentro dos parâmetros.",
        recomendacoes: null,
        necessitaReavaliacao: false,
        status: "publicada",
        biNumero: `BG nº 020, de ${addDias(data, -58)}`,
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        publicadoEm: new Date(),
        criadoPor: presidente.id,
      },
      {
        ataNumero: `ATA Nº 0005/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: patricia.id,
        atestadoId: null,
        medicoId: medico.id,
        tipo: "inicial",
        dataInspecao: addDias(data, -100),
        parecer: "necessita_lts",
        cid: "F32.1",
        enquadramentoLegal: "Estatuto dos Policiais Militares de Rondônia — LTS",
        diasAfastamento: 120,
        dataInicio: addDias(data, -100),
        dataFim: addDias(data, 19),
        restringeAtividade: true,
        descricaoClinica:
          "Episódio depressivo moderado em tratamento psiquiátrico regular.",
        examesRealizados: "Avaliação psiquiátrica com escala HAM-D 18.",
        recomendacoes: "Acompanhamento psiquiátrico quinzenal. Dispensa de escala de serviço.",
        necessitaReavaliacao: true,
        dataReavaliacao: addDias(data, 12),
        status: "homologada",
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        criadoPor: medico.id,
      },
      {
        ataNumero: `ATA Nº 0006/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: eduardo.id,
        atestadoId: null,
        medicoId: medico.id,
        tipo: "inicial",
        dataInspecao: addDias(data, -45),
        parecer: "apto",
        cid: null,
        enquadramentoLegal: null,
        diasAfastamento: 0,
        restringeAtividade: false,
        descricaoClinica: "Avaliação para fins de estágio operacional. Sem intercorrências.",
        examesRealizados: "Avaliação cardiorrespiratória e TAF válido.",
        recomendacoes: null,
        necessitaReavaliacao: false,
        status: "emitida",
        criadoPor: medico.id,
      },
      {
        ataNumero: `ATA Nº 0007/${data.slice(0, 4)} - JIS/PMRO`,
        militarId: mariana.id,
        atestadoId: null,
        medicoId: presidente.id,
        tipo: "reavaliacao",
        dataInspecao: addDias(data, -400),
        parecer: "agregacao",
        cid: "M25.5",
        enquadramentoLegal: "Estatuto dos Policiais Militares de Rondônia — Agregação",
        diasAfastamento: 380,
        dataInicio: addDias(data, -400),
        dataFim: addDias(data, -21),
        restringeAtividade: true,
        descricaoClinica:
          "Artropatia degenerativa de joelho com múltiplas cirurgias e reabilitação prolongada.",
        examesRealizados: "RNM de joelho com condropatia avançada.",
        recomendacoes: "Manter acompanhamento ortopédico. Avaliar proposta de reforma.",
        necessitaReavaliacao: true,
        dataReavaliacao: addDias(data, -5),
        status: "publicada",
        biNumero: `BG nº 180, de ${addDias(data, -398)}`,
        homologadoPor: presidente.id,
        homologadoEm: new Date(),
        publicadoEm: new Date(),
        criadoPor: presidente.id,
      },
    ]);

  const [
    ataAlmeida,
    ataRafael,
    ataWagner,
    ataMota,
    ataPatricia,
    ataEduardo,
    ataMariana,
  ] = novasInspecoes;

  await inserirVarios("afastamentos", [
    {
      militarId: almeida.id,
      inspecaoId: ataAlmeida.id,
      tipo: "lts",
      dataInicio: addDias(data, -17),
      dataFim: addDias(data, -8),
      dias: 10,
      situacao: "encerrado",
      observacoes: "Acumulado em 12 meses: 10 dia(s).",
    },
    {
      militarId: almeida.id,
      inspecaoId: null,
      tipo: "tratamento_saude",
      dataInicio: addDias(data, -40),
      dataFim: addDias(data, -33),
      dias: 8,
      situacao: "encerrado",
      observacoes: "Licença anterior homologada em ata de exercício findo.",
    },
    {
      militarId: rafael.id,
      inspecaoId: ataRafael.id,
      tipo: "lts",
      dataInicio: addDias(data, -11),
      dataFim: addDias(data, 48),
      dias: 60,
      situacao: "vigente",
      observacoes: "Acumulado em 12 meses: 60 dia(s).",
    },
    {
      militarId: rafael.id,
      inspecaoId: null,
      tipo: "tratamento_saude",
      dataInicio: addDias(data, -220),
      dataFim: addDias(data, -190),
      dias: 31,
      situacao: "encerrado",
      observacoes: "Afastamento anterior.",
    },
    {
      militarId: patricia.id,
      inspecaoId: ataPatricia.id,
      tipo: "lts",
      dataInicio: addDias(data, -100),
      dataFim: addDias(data, 19),
      dias: 120,
      situacao: "vigente",
      observacoes: "Acumulado em 12 meses: 120 dia(s).",
    },
    {
      militarId: patricia.id,
      inspecaoId: null,
      tipo: "tratamento_saude",
      dataInicio: addDias(data, -300),
      dataFim: addDias(data, -251),
      dias: 50,
      situacao: "encerrado",
      observacoes: "Afastamento anterior.",
    },
    {
      militarId: mariana.id,
      inspecaoId: ataMariana.id,
      tipo: "agregacao",
      dataInicio: addDias(data, -400),
      dataFim: addDias(data, -21),
      dias: 380,
      situacao: "vigente",
      agregadoDesde: addDias(data, -320),
      observacoes: "Agregada — afastamento superior a 2 anos em curso de análise.",
    },
    {
      militarId: mariana.id,
      inspecaoId: null,
      tipo: "agregacao",
      dataInicio: addDias(data, -720),
      dataFim: addDias(data, -401),
      dias: 320,
      situacao: "encerrado",
      observacoes: "Prorrogações anteriores.",
    },
    {
      militarId: wagner.id,
      inspecaoId: ataWagner.id,
      tipo: "dispensa_atividade",
      dataInicio: addDias(data, -25),
      dataFim: addDias(data, 5),
      dias: 31,
      situacao: "vigente",
      observacoes: "Restrição de atividade sem afastamento do serviço.",
    },
  ]);

  await inserirVarios("convocacoes", [
    {
      militarId: patricia.id,
      inspecaoId: ataPatricia.id,
      motivo: "Reavaliação após Necessita de LTS — ATA Nº 0005",
      emitidaEm: addDias(data, -20),
      dataLimite: addDias(data, 12),
      canal: "Boletim Geral",
      status: "notificada",
      criadoPor: secretaria.id,
    },
    {
      militarId: mariana.id,
      inspecaoId: ataMariana.id,
      motivo: "Reavaliação obrigatória — prazo de agregação excedido",
      emitidaEm: addDias(data, -15),
      dataLimite: addDias(data, -2),
      canal: "Boletim Geral / Contato telefônico",
      status: "pendente",
      criadoPor: secretaria.id,
    },
    {
      militarId: rafael.id,
      inspecaoId: ataRafael.id,
      motivo: "Reavaliação ortopédica antes do término do afastamento",
      emitidaEm: addDias(data, -5),
      dataLimite: addDias(data, 41),
      canal: "Boletim Geral",
      status: "pendente",
      criadoPor: medico.id,
    },
    {
      militarId: wagner.id,
      inspecaoId: ataWagner.id,
      motivo: "Reavaliação cardiológica de controle",
      emitidaEm: addDias(data, -25),
      dataLimite: addDias(data, 3),
      canal: "Contato telefônico",
      status: "pendente",
      criadoPor: presidente.id,
    },
  ]);

  await inserirVarios("auditoria", [
    {
      usuarioId: secretaria.id,
      usuarioNome: secretaria.nome,
      papel: secretaria.papel,
      acao: "CADASTRAR_MILITAR",
      entidade: "militar",
      entidadeId: String(pimentel.id),
      resumo: `${pimentel.postoGraduacao} ${pimentel.nome} (${pimentel.re}) cadastrado`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 52),
    },
    {
      usuarioId: secretaria.id,
      usuarioNome: secretaria.nome,
      papel: secretaria.papel,
      acao: "INSERIR_ATESTADO",
      entidade: "atestado",
      entidadeId: String(atAlmeida.id),
      resumo: `Atestado ${atAlmeida.protocolo} inserido pela secretaria`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 40),
    },
    {
      usuarioId: medico.id,
      usuarioNome: medico.nome,
      papel: medico.papel,
      acao: "REGISTRAR_PARECER",
      entidade: "inspecao",
      entidadeId: String(ataAlmeida.id),
      resumo: `${ataAlmeida.ataNumero} — Necessita de LTS (10 dia(s))`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 38),
    },
    {
      usuarioId: presidente.id,
      usuarioNome: presidente.nome,
      papel: presidente.papel,
      acao: "HOMOLOGAR_ATA",
      entidade: "inspecao",
      entidadeId: String(ataAlmeida.id),
      resumo: `Ata ${ataAlmeida.ataNumero} homologada`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 36),
    },
    {
      usuarioId: presidente.id,
      usuarioNome: presidente.nome,
      papel: presidente.papel,
      acao: "PUBLICAR_BI",
      entidade: "inspecao",
      entidadeId: String(ataAlmeida.id),
      resumo: `Extrato publicado no ${ataAlmeida.biNumero}`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 35),
    },
    {
      usuarioId: secretaria.id,
      usuarioNome: secretaria.nome,
      papel: secretaria.papel,
      acao: "MUDAR_STATUS_ATESTADO",
      entidade: "atestado",
      entidadeId: String(atJuliana.id),
      resumo: `Atestado ${atJuliana.protocolo}: pendente → em_analise`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 90),
    },
    {
      usuarioId: pessoal.id,
      usuarioNome: pessoal.nome,
      papel: pessoal.papel,
      acao: "CONSULTAR_RELATORIO",
      entidade: "relatorio",
      entidadeId: "S1",
      resumo: "Relatório de aptos/inaptos exportado para a Seção de Pessoal",
      criadoEm: new Date(Date.now() - 1000 * 60 * 30),
    },
    {
      usuarioId: secretaria.id,
      usuarioNome: secretaria.nome,
      papel: secretaria.papel,
      acao: "RECEBER_ATESTADO_MILITAR",
      entidade: "atestado",
      entidadeId: String(atLucas.id),
      resumo: `Atestado ${atLucas.protocolo} recebido por envio digital do militar`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 20),
    },
    {
      usuarioId: null,
      usuarioNome: "sistema",
      papel: null,
      acao: "RECEBER_ATESTADO_MILITAR",
      entidade: "atestado",
      entidadeId: String(atThiago.id),
      resumo: `Atestado ${atThiago.protocolo} recebido por envio digital do militar`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 70),
    },
    {
      usuarioId: null,
      usuarioNome: "sistema",
      papel: null,
      acao: "RECEBER_ATESTADO_MILITAR",
      entidade: "atestado",
      entidadeId: String(atPimentel.id),
      resumo: `Atestado ${atPimentel.protocolo} recebido por envio digital do militar`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 48),
    },
    {
      usuarioId: secretaria.id,
      usuarioNome: secretaria.nome,
      papel: secretaria.papel,
      acao: "MUDAR_STATUS_ATESTADO",
      entidade: "atestado",
      entidadeId: String(atFernanda.id),
      resumo: `Atestado ${atFernanda.protocolo}: pendente → em_analise`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 8),
    },
    {
      usuarioId: medico.id,
      usuarioNome: medico.nome,
      papel: medico.papel,
      acao: "REGISTRAR_PARECER",
      entidade: "inspecao",
      entidadeId: String(ataEduardo.id),
      resumo: `${ataEduardo.ataNumero} — Apto`,
      criadoEm: new Date(Date.now() - 1000 * 60 * 60 * 100),
    },
  ]);

  // Normaliza dias dos afastamentos (consistência do acumulado).
  const todosAfastamentos = await all<{ id: number; dataInicio: string; dataFim: string; dias: number }>("afastamentos");
  for (const a of todosAfastamentos) {
    const dias = diasInclusive(a.dataInicio, a.dataFim);
    if (dias !== a.dias) {
      await atualizar("afastamentos", { dias }, "id", a.id);
    }
  }
}

const SETORES_PADRAO = ["Recepção", "Secretaria", "Sala Médica", "Arquivo", "Perícia", "Direção"];
export async function ensureSetores(): Promise<void> {
  if (await contar("setores") > 0) return;
  await inserirVarios("setores", SETORES_PADRAO.map((nome) => ({ nome })));
}


